
#include "libdragon.h"

#define LIBDRAGON_VERSION_MAJOR 2
#define LIBDRAGON_VERSION_MINOR 0
#define LIBDRAGON_VERSION_REVISION 1

libdragon_version_t libdragon_version = { LIBDRAGON_VERSION_MAJOR, LIBDRAGON_VERSION_MINOR, LIBDRAGON_VERSION_REVISION };
